eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

microservices:
    payment-service:
        endpoints:
            fetchPaymentById:
                uri: http://PAYMENTSERVICE/payments/
    user-service:
        endpoints:
            fetchUserById:
                uri: http://USERSERVICE/users/

